title       = "ncbinucleotide"
baseURL     = "https://ncbinucleotide-cli.tamnd.com/"
description = "A command line for ncbinucleotide."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ncbinucleotide-cli"
